### ISSUE TITLE
Use color-blind friendly color! Or let us configure colors.

### ISSUE THREAD

**Issue by ghost** [clupascu/regex-crossword-goodies#2]
.clue-error and .clue-ok are too close in color to be easily distinguished with thin fonts.

**Comment by clupasq** [comment]
Good point!

Would it be OK to use red/blue instead of red/green?
Or to alter other aspects of the text (like background, or weight) only in case it's wrong?

Please let me know your thoughts on this.

Thanks!

**Comment by ghost** [comment]
Red for error and blue for OK would be fine. In fact that's what I ended up
with when I realized I could use Stylish to change it myself.  :)

**Comment by clupasq** [comment]
Wow, didn't know about Stylish - cool extension. :)
I will update the colors when I have some time.

Thanks a lot: I learned two good things today.
