### ISSUE TITLE
Link to debuggex.com

### ISSUE THREAD

**Issue by ghost** [clupascu/regex-crossword-goodies#3]
Suggestion: each regex could link to debuggex.com

**Comment by clupasq** [comment]
That's a great idea! :+1: I was thinking of doing this, but with https://regex101.com/.

Unfortunately I found no way to pass a regex as a URL parameter. Is this possible with debuggex.com?

**Comment by ghost** [comment]
No, not with debuggex. However, this alternative site works with a URL:
https://regexper.com/#abcd

On Wed, May 11, 2016 at 2:23 AM, Cristian Lupașcu notifications@github.com
wrote:

> That's a great idea! [image: :+1:] I was thinking of doing this, but with
> https://regex101.com/.
> 
> Unfortunately I found no way to pass a regex as a URL parameter. Is this
> possible with debuggex.com?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/wolfascu/regex-crossword-goodies/issues/3#issuecomment-218372549

## 

_-- *
*Ross Presser_
DevOps Engineer
Aleyant
312 S. Hale Street
Wheaton, IL 60187
Phone: 800.571.2138 x712
Fax: 630.929.0104
Email:  rpresser@aleyant.comrpresser@aleyant.com
http://aleyant.com/page/web-to-print-solutions-from-aleyant-systems
www.Aleyant.com http://www.aleyant.com/

---

Confidentiality Notice:

This E-Mail transmission (and/or the documents accompanying it) may contain
information belonging to the sender which is confidential, privileged
and/or exempt from disclosure under applicable law. The information is
intended only for the use of the individual(s) or entity named above. If
you are not the intended recipient, you are hereby notified that any
disclosure, copying, distribution or the taking of any action in reliance
on the contents of this information is strictly prohibited. If you have
received this E-Mail transmission in error, please immediately notify us by
return E-Mail or telephone to arrange for return of its contents including
any documents.

**Comment by clupasq** [comment]
Implemented in 052474934e6b31d728e4d013d7dfe0ea25334d69.
